### PR TITLE
fixes #72: Loading identical modules

### LINKED ISSUE #72: Fails to bundle when there are identical modules
If there are two modules in the graph with identical ASTs, bandolier will not build the graph. For example:

```sh
./bin/bandolier.sh a.js
```

```js
// a.js
import './b.js';
import './c.js';
```
```js
// b.js
console.log(0);
```
```js
// c.js
console.log(0);
```

results in
```
Exception in thread "main" com.shapesecurity.bandolier.es2017.loader.ModuleLoaderException: Module Loader Exception: module /bandolier/a.js cannot be loaded: Not all modules were scheduled: 2 / 3.
Unscheduled modules:

	at com.shapesecurity.bandolier.es2017.Bundler.bundleString(Bundler.java:115)
	at com.shapesecurity.bandolier.es2017.Bundler.bundle(Bundler.java:79)
	at com.shapesecurity.bandolier.es2017.Main.main(Main.java:48)
Caused by: java.lang.RuntimeException: Not all modules were scheduled: 2 / 3.
Unscheduled modules:

	at com.shapesecurity.bandolier.es2017.transformations.ImportExportConnector.combineModules(ImportExportConnector.java:463)
	at com.shapesecurity.bandolier.es2017.bundlers.PiercedModuleBundler.bundleEntrypoint(PiercedModuleBundler.java:47)
	at com.shapesecurity.bandolier.es2017.Bundler.bundleString(Bundler.java:113)
	... 2 more
```

### PR DESCRIPTION
**Pull request by hewholived**

### CODE REVIEW

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/ImportExportConnector.java [hunk 1]
```diff
@@ -215,14 +215,14 @@ private ImportExportConnector() {
 	 * @param moduleAncestorIndex  internal counter, always initialise to 0
 	 * @return an index and state of a module scheduled. the index is used internally, and is to be discarded. success can be determined by checking the module state is `ModuleState.INSTANTIATED`
 	 */
-	private static Pair<Integer, ModuleState> scheduleModule(@Nonnull Module module, @Nonnull LinkedList<Module> schedule, @Nonnull HashSet<Module> scheduleSet, @Nonnull HashMap<Module, LinkedList<Module>> dependingOn, int index, @Nonnull LinkedList<Module> stack, @Nonnull HashSet<Module> stackSet, @Nonnull HashMap<Module, Integer> moduleAncestorIndex) {
-		if (scheduleSet.contains(module)) {
+	private static Pair<Integer, ModuleState> scheduleModule(@Nonnull Module module, @Nonnull LinkedList<Module> schedule, @Nonnull IdentityHashMap scheduleSet, @Nonnull HashMap<Module, LinkedList<Module>> dependingOn, int index, @Nonnull LinkedList<Module> stack, @Nonnull IdentityHashMap stackSet, @Nonnull HashMap<Module, Integer> moduleAncestorIndex) {
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/transformations/ImportExportConnector.java]: There are still a few `HashMap<Module, Foo>` types in this file. It seems like those would need to be changed too - e.g. if you have two identical modules which are in different paths, they can have different dependencies (and etc). Should those be changed? Either way, can you add a test where the identical modules are in different paths, and therefore have different dependencies? Something like

```js
// ./a.js
import { b as b1 } from './b.js';
import { b as b2 } from './subdir/b.js';
export var result = b1 + b2;

// ./b.js
export { b } from './c.js';

// ./c.js
export var b = 2;

// ./subdir/b.js
export { b } from './c.js';

// ./subdir/c.js
export var b = 3;
``` 

Alternatively, it might be easier to just make a `ModuleWrapper` type that just wraps a `Module` and does not define `hashCode`/`equals`, so there's no risk of accidentally using a `HashMap` instead of an `IdentityHashMap`.

Comment (hewholived) [reply src/main/java/com/shapesecurity/bandolier/es2017/transformations/ImportExportConnector.java]: I like the `ModuleWrapper` idea better. Though, I need to make it a subclass of `Module` and override the `equals/hashCode` functions to make it work because of a number of places where I have change the code this way (avoiding rewrite of accesses to `directives` and `items` properties) will be smaller compared to when I implement it as a wrapper.

File: src/test/java/com/shapesecurity/bandolier/es2017/BundlerTest.java [hunk 2]
```diff
@@ -307,6 +306,34 @@ public void testImportOrdering() throws Exception {
...
+	}
+
+	@Test
+	public void testIdenticalModuleImportWithSubdirs() throws Exception {
+		Map<String, String> modules = new HashMap<>();
+		modules.put("/a.js",
+			"import { b as b1 } from './b.js';\n" +
+			"import { b as b2 } from './subdir/b.js';\n" +
+			"export var result = b1 + b2;");
+		TestLoader localLoader = new TestLoader(modules);
```
Comment (bakkot) [inline src/test/java/com/shapesecurity/bandolier/es2017/BundlerTest.java]: Nit: this should go down with `testResult`. (Same in the other test.)

**Review by bakkot — APPROVED** [review]
LGTM other than nit
