### PR TITLE
Fix variable name shadowing for aliased imports, version 3.3.0.

### LINKED ISSUE #66: Pierced module bundler does not avoid shadowing names
Suppose we have 

`a.js`:
```js
export function thing() {
  return 42;
}
```

`b.js`:
```js
import { thing as other } from './a.js';

window.x = function () {
  return function thing() {
    other();
  };
};
```

Running `bandolier` with default options and passing `b.js` as the entrypoint produces

```js
(function(e) {
  'use strict';
  window.x = function() {
    return function thing() {
      thing();
    };
  };
  var t = { __proto__: null };
  if (e.Symbol) e.Object.defineProperty(t, e.Symbol.toStringTag, { value: 'Module' });
  t = e.Object.freeze(t);
  return t;
})(this);
```

That's wrong: `thing` should not call itself, it should call the function which returns 42.

### PR DESCRIPTION
**Pull request by Protryon**
Fixes #66.

### CODE REVIEW

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableCollisionResolver.java [hunk 1]
```diff
@@ -18,36 +21,97 @@ private VariableCollisionResolver() {
...
+			ScopeLookup lookup = scopeLookups.get(pair.left).fromJust();
+			return reference.node instanceof IdentifierExpression ?
+				lookup.findVariableReferencedBy((IdentifierExpression) reference.node) :
+				lookup.findVariableReferencedBy((AssignmentTargetIdentifier) reference.node);
+		})), acc)), ImmutableSet.emptyUsingIdentity());
+
+		VariableNameGenerator nameGenerator = new VariableNameGenerator(allNames.union(throughVariables.map(variable -> variable.name)));
+
+		HashTable<Module, HashTable<Variable, String>> renamingMaps =
+			allDeclaredVariables.entries().filter(pair -> pair.right.length() > 1)
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableCollisionResolver.java:75]: This is pretty hard to read, and also looks like it contains some duplicate code. Can you, for example, factor out the

```java
(pair, subAcc) ->
  subAcc.put(
    pair.left,
    pair.right.foldLeft(
      (variableAcc, renaming) ->
        variableAcc.put(renaming, nameGenerator.next()),
      subAcc.get(pair.left).orJust(HashTable.emptyUsingIdentity())
    )
  ),
```
bits to a static method with a meaningful name?

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableDeclarationExtractor.java [hunk 2]
```diff
@@ -0,0 +1,39 @@
...
+import com.shapesecurity.shift.es2017.scope.Scope;
+import com.shapesecurity.shift.es2017.scope.ScopeAnalyzer;
+import com.shapesecurity.shift.es2017.scope.ScopeLookup;
+import com.shapesecurity.shift.es2017.scope.Variable;
+
+import javax.annotation.Nonnull;
+import java.util.List;
+import java.util.stream.Collectors;
+
+// determines all declared global variables for a module, linked to a scope analysis variable
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableDeclarationExtractor.java:24]: "global" continues to be wrong I think.

File: src/main/java/com/shapesecurity/bandolier/es2017/bundlers/PiercedModuleBundler.java [hunk 3]
```diff
@@ -26,7 +26,6 @@
 	@Override
 	public @NotNull Script bundleEntrypoint(BundlerOptions options, String entry, Map<String, Module> modules) {
 		HashTable<String, Module> newModules = HashTable.emptyUsingEquality();
-		HashTable<String, ImmutableSet<Pair<String, String>>> removedImports = HashTable.emptyUsingIdentity();
 		for (Map.Entry<String, Module> mapEntry : modules.entrySet()) {
 			Module module = mapEntry.getValue();
 			module = new Module(module.directives, module.items.map(item -> {
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/bundlers/PiercedModuleBundler.java]: This isn't really relevant to this PR, but it looks to me like the `if (options.exportStrategy == BundlerOptions.ExportStrategy.ALL_GLOBALS)` below could be pulled out of the lambda, no? So that you'd only perform the `.map` at all if the test there is satisfied.

**Review by bakkot — APPROVED** [review]
