### PR TITLE
Fix name collision with generated module names and function local assignments, version 3.2.3

### LINKED ISSUE #59: Name collision with generated module names and function local assignments
The import assignment resolver fails to see generated module names as different from function locals of the same name, leading to runtime or compile-time errors being thrown for assignment to an import, when no such assignment happened.

### PR DESCRIPTION
**Pull request by Protryon**
The import assignment resolver fails to see generated module names as different from function locals of the same name. To avoid excessive scope analysis throughout execution, all possible name collisions are handled in the variable name generator to avoid this. Fixes #59.

### CODE REVIEW

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableCollisionResolver.java [hunk 1]
```diff
@@ -20,18 +20,19 @@ private VariableCollisionResolver() {
...
+		HashTable<String, ImmutableSet<String>> globalNames = modules.foldLeft((acc, module) -> GlobalVariableExtractor.extractAllDeclaredVariables(module.right, globalScopes.get(module.left).fromJust(), new ScopeLookup(globalScopes.get(module.left).fromJust())).entries().map(pair -> pair.left).foldLeft((subAcc, name) -> subAcc.put(name, module.left), acc), MultiHashTable.<String, String>emptyUsingEquality()).toHashTable(ImmutableList::uniqByEquality);
+		HashTable<String, ImmutableSet<String>> allNames = modules.foldLeft((acc, module) -> VariableReferenceExtractor.extractAllReferencedVariables(module.right, globalScopes.get(module.left).fromJust(), new ScopeLookup(globalScopes.get(module.left).fromJust())).entries().map(pair -> pair.left).foldLeft((subAcc, name) -> subAcc.put(name, module.left), acc), MultiHashTable.<String, String>emptyUsingEquality()).toHashTable(ImmutableList::uniqByEquality);
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableCollisionResolver.java]: It looks like you only need the keys here. If that's so, you shouldn't build the whole hash table.

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableReferenceExtractor.java [hunk 2]
```diff
@@ -0,0 +1,90 @@
...
+import com.shapesecurity.shift.es2017.scope.GlobalScope;
+import com.shapesecurity.shift.es2017.scope.ScopeAnalyzer;
+import com.shapesecurity.shift.es2017.scope.ScopeLookup;
+import com.shapesecurity.shift.es2017.scope.Variable;
+
+import javax.annotation.Nonnull;
+import java.util.List;
+import java.util.stream.Collectors;
+
+// determines all declared global variables for a module, linked to a scope analysis variable
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableReferenceExtractor.java]: I think this comment is now wrong.

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableReferenceExtractor.java [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+		DeclaredVariableReducer reducer = new DeclaredVariableReducer(globalScope, lookup);
+		return Director.reduceProgram(reducer, module);
+	}
+
+	public static MultiHashTable<String, Variable> extractAllReferencedVariables(@Nonnull Program module) {
+		GlobalScope globalScope = module instanceof Module ? ScopeAnalyzer.analyze((Module) module) : ScopeAnalyzer.analyze((Script) module);
+		return extractAllReferencedVariables(module, globalScope, new ScopeLookup(globalScope));
+	}
+
+	private static final class DeclaredVariableReducer extends MonoidalReducer<MultiHashTable<String, Variable>>  {
```
Comment (bakkot) [inline src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableReferenceExtractor.java]: Is there a reason to do this with a reducer, instead of just extracting the relevant information from the Scope object directly?

File: src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableCollisionResolver.java (hunk 1 above)
Comment (bakkot) [reply src/main/java/com/shapesecurity/bandolier/es2017/transformations/VariableCollisionResolver.java]: And in fact `VariableReferenceExtractor.extractAllReferencedVariables` can probably be simplified to just give the strings.

**Review by bakkot — APPROVED** [review]
